[tool.poetry]
name = "yogurt-optimization"
version = "0.1.0"
description = ""
authors = ["@taxfree-python"]

[tool.poetry.dependencies]
python = "^3.10"
optuna = "^3.0"
jupyterlab = "*"
matplotlib = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
